### ISSUE TITLE
Did not complete homework : (

### ISSUE THREAD

**Issue by heathersansone** [heathersansone/chatApp#1]
I made an attempt at the Chat App homework and it is wildly unsuccessful.  So far the only thing this app can do is print out the list of prior messages anytime someone new connects.  I have no idea what this needs to work and I tried to make a function to figure out a way to send new messages to existing clients, but I don't have any idea how to go about it.

**Comment by annarankin** [comment]
Hey Heather, I hope the solution we went over together after class was helpful!
